yusukesugahara/freemarket_sample_47a

- app/assets/javascripts/brands.coffee
- app/assets/javascripts/categories.coffee
- app/assets/javascripts/comments.coffee
- app/assets/javascripts/mypages.coffee
- app/assets/javascripts/sells.coffee
- app/assets/javascripts/tops.coffee
- app/assets/stylesheets/brands.scss
- app/assets/stylesheets/categories.scss
- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/mypages.scss
- app/assets/stylesheets/sells.scss
- app/assets/stylesheets/tops.scss
- app/controllers/brands_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/mypages_controller.rb
- app/controllers/sells_controller.rb
- app/controllers/tops_controller.rb
- app/helpers/brands_helper.rb
- app/helpers/categories_helper.rb
- app/helpers/comments_helper.rb
- app/helpers/mypages_helper.rb
- app/helpers/sells_helper.rb
- app/helpers/tops_helper.rb
- test/controllers/brands_controller_test.rb
- test/controllers/categories_controller_test.rb
- test/controllers/comments_controller_test.rb
- test/controllers/mypages_controller_test.rb
- test/controllers/sells_controller_test.rb
- test/controllers/tops_controller_test.rb
> Created controller

- Gemfile
- Gemfile.lock
- config/unicorn.rb
#WHAT
Unicornの実装を行う
#WHY
Ruby on Railsアプリケーションを本番環境で動作させるため
> [WIP]Unicornの実装

- config/database.yml
#WHAT
database_yml設定
#WHY
アプリケーションを起動するため
> edit_database_yml

- Capfile
- Gemfile
- Gemfile.lock
- config/database.yml
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/unicorn.rb
#WHAT
Capistranoをインストールした
#WHY
自動デプロイツールで自動デプロイをするのに必要のため
> Capistrano設定

- app/views/tops/index.html.haml
- config/routes.rb
#WHAT
ルーティングエラーの解消とビューの修正
#WHY
ルーティングエラーの解消とビューの修正のため
> Correction route_tops_view

- app/assets/stylesheets/_mypages.scss
#WHAT
マイページのshowアクションビューにバグを発見したため修正を行った。
バグ内容:お知らせリスト上にマウスをのせると、ユーザーアイコンや名前が反応する。
修正内容:お知らせリスト上にマウスをのせてもユーザーアイコンや名前が反応しないように修正した。
結果:修正完了
#WHY
正しい仕様ではないためバグを修正した。
> correction_mypage_show_action

- README.md
#WHAT
DB設計の修正
#WHY
DB設計に誤りがあったため
> edit_readme_correction_db_design_1

- app/assets/stylesheets/_tops.scss
- app/assets/stylesheets/signup/_sms_confirmations.scss
- app/controllers/application_controller.rb
- app/views/mypages/edit.html.haml
- app/views/mypages/identifications/new.html.haml
- app/views/mypages/logouts/index.html.haml
- app/views/mypages/shered/_header.html.haml
- app/views/mypages/show.html.haml
- app/views/shered/_fotter.html.haml
- app/views/shered/_header.html.haml
- app/views/signup/addresses/new.html.haml
- app/views/signup/sms_confirmations/index.html.haml
- app/views/signup/sms_confirmations/sms/index.html.haml
- app/views/tops/index.html.haml
- app/views/tops/new.html.haml
#WHAT
各ボタンに対し、リンクを貼った。
#WHY
ボタンを押すと各ページに移動できるようにするため
> edit_view_files_add_links

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/_breadcrumbs.scss
- app/assets/stylesheets/application.scss
- app/views/mypages/cards/index.html.haml
- app/views/mypages/cards/new.html.haml
- app/views/mypages/edit.html.haml
- app/views/mypages/identifications/new.html.haml
- app/views/mypages/logouts/index.html.haml
- app/views/mypages/shered/_header.html.haml
- app/views/mypages/show.html.haml
- app/views/tops/index.html.haml
- config/breadcrumbs.rb
> breadcrumb

- app/views/shered/_header.html.haml
#WHAT
カテゴリー表示機能のパフォーマンス改善
#WHY
カテゴリー表示機能のパフォーマンス改善のため
> for_preformance_correction1

- db/migrate/20190404065843_devise_create_users.rb
- db/migrate/20190415101008_remove_customer_id_from_users.rb
#WHAT
マイグレーションファイルの修正
#WHY
マイグレーションファイルの修正のため
> migration_file_correction1

- app/assets/javascripts/items.js
#WHAT
Js記述の修正
#WHY
Js記述が誤っていたため
> Js_correction1

- app/assets/javascripts/item_new.js
- app/assets/stylesheets/_items_new.scss
- app/views/items/new.html.haml
#WHAT
商品出品画面の修正
＃WHY
商品出品画面の修正のため
> item_new_correction2

- app/assets/javascripts/item_new.js
#WHAT
商品出品機能の修正
#WHY
商品出品機能にバグが発生したため
> item_new_correction3

- app/assets/javascripts/item_edit.js
#WAHT
商品編集機能の修正
#WHY
商品編集機能の修正のため
> item_edit_correction1

- app/controllers/mypages/identifications_controller.rb
- app/views/mypages/identifications/new.html.haml
- app/views/signup/addresses/new.html.haml
- app/views/signup/sms_confirmations/index.html.haml
- db/data_reading_files/users.csv
- db/seeds.rb
#WHAT
signup画面の修正
seedデータへのテストユーザー２の追加
#WHY
signup画面の修正のため
他の方に見ていただけるようにするため
> correction_signup_view1

- app/controllers/application_controller.rb
#WHAT
ベーシック認証の実装
#WHY
本番環境を閲覧できる人を制限するため
> add_basic_authentication

- app/assets/javascripts/items.js
#WHAT
カテゴリ機能の修正
#WHY
カテゴリ機能の修正のため(第二階層で孫要素がない場合にも孫要素のボックスが表示されるバグの修正のため)
> correction_category_function

- app/assets/javascripts/item_edit.js
- app/assets/javascripts/item_new.js
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/edit.html.haml
#WHAT
商品編集機能の修正
#WHY
商品出品機能強化に伴う商品編集機能の修正のため
> item_edit_correction2

- app/assets/javascripts/item_edit.js
- app/assets/javascripts/item_new.js
- app/views/items/edit.html.haml
#WHAT
商品編集機能の修正
（カテゴリ選択機能の修正）
#WHY
商品編集機能の修正のため
（カテゴリ選択機能の修正）
> item_edit_correction3

- app/assets/javascripts/search.js
- app/controllers/searches_controller.rb
- app/views/searches/index.html.haml
#WHAT
詳細検索機能の修正
#WHY
詳細検索機能の修正のため
> moredetail_search_correction1
